home/urls.py
from django.urls import path
from .views import * 

app_name = 'home' 

urlpatterns = [
    path('', homepage, name='home'),
    path('who-we-are', aboutus, name='who-we-are'),
   
    path('start-a-project', StartAProject.as_view(), name='start-a-project'),
     path('thank-you', thankyou, name='thank-you'),
]

scriptdesk/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include 
from home.views import error404, error500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    

]


handler404 = error404
handler500 = error500




if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models
from PIL import Image
# Create your models here.




class Portfolio(models.Model):
    category = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    

home/forms.py
from django import forms

class StartAProjectForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'id': 'con_name',
        'class': 'form-inp requie',
        'placeholder': 'Name'

    }))

    email = forms.CharField(required=True, widget=forms.TextInput(attrs={
    
        'id': 'con_email',
        'class': 'form-inp requie',
        'placeholder': 'Email'


    }))

    msg = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'requie',
        'id': 'con_message',
        'rows':8,
        'placeholder': 'Leave a Message!'

    }))

home/views.py
from django.contrib import messages
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, HttpResponseServerError
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.core.mail import EmailMultiAlternatives, send_mail, EmailMessage
from django.template.loader import render_to_string
from django.template import RequestContext
from django.utils.encoding import force_bytes
from django.views.defaults import page_not_found
from .forms import *


# Create your views here.

def error404(request, exception):
    return page_not_found(request, exception, 'errors/404.html')

def error500(request):
    return render(request, 'errors/500.html')

def homepage(request):
        
    template = 'home/index.html'
    
    return render(request, template)

def aboutus(request):
        
    template = 'home/about.html'
    
    return render(request, template)

class StartAProject(View):
    
    def get(self, request, *args, **kwargs):
        template = 'home/contact.html'

        form = StartAProjectForm()

        context = {
            'form': form
        }

        return render(self.request, template, context)

    def post(self, request, *args, **kwargs):

        form = StartAProjectForm(self.request.POST or None)

        try:
            if form.is_valid():
                name = form.cleaned_data.get('name')
                email = form.cleaned_data.get('email')
                msg = form.cleaned_data.get('msg')

                subject, from_email, to = 'New Project Entry from Website', 'SCRIPT DESK <dev@scriptdeskng.com>', ['shola.albert@gmail.com', 'hello@scriptdeskng.com', 'biz@scriptdeskng.com']
                
                html_content = render_to_string(
                    'home/email_from_site.html', {'email': email, 'name': name, 'msg': msg })
                msg = EmailMessage(subject, html_content, from_email, to)
                msg.content_subtype = "html"
                msg.send()

                return redirect('home:thank-you')

        except (ValueError, NameError, TypeError) as error:
            err_msg = str(error)
            print(err_msg)
        except:
            print("Unexpected Error")
            raise

def thankyou(request):

    template = 'home/thankyou.html'

    return render(request, template)

home/templates/home/about.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %} Who We Are {% endblock title %}
{% block content %}

<div class="container">
    <div class="page-content about-page">
        <div class="page-title top_90">
            <h1 class="title">About Us</h1>
            <div class="zigzag">
                <svg viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns="http://www.w3.org/2000/svg">
                 <path d="M1.357,12.26 10.807,2.81 20.328,12.332
                    29.781,2.879 39.223,12.321 48.754,2.79  58.286,12.321"/>
                </svg>
            </div>
        </div>
        <!-- About text -->
        <div class="col-lg-8 offset-lg-2 text-center padding_30">
            <p class="about-text">We are experts in web and digital marketing, content management and programming, platform development and management <br>
We are passionate about quality development, best practices, security.</p>
            
            <!-- services -->
            <div class="row services padding_90">
                <div class="col-md-3 col-sm-6 service text-center">
                    <i class="icon-desktop"></i>
                    <h3 class="title top_15">Web Development</h3>
                    <!-- <p>Her extensive perceived may any sincerity extremity.</p>  -->
                </div>
                <div class="col-md-3 col-sm-6 service text-center">
                    <i class="icon-tools"></i>
                    <h3 class="title top_15">Branding Identity</h3>
                    <!-- <p>Her extensive perceived may any sincerity extremity.</p>  -->
                </div>
                <div class="col-md-3 col-sm-6 service text-center">
                    <i class="icon-paintbrush"></i>
                    <h3 class="title top_15">Web & Digital Marketing</h3>
                    <!-- <p>Her extensive perceived may any sincerity extremity.</p>  -->
                </div>
                <div class="col-md-3 col-sm-6 service text-center">
                    <i class="icon-lightbulb"></i>
                    <h3 class="title top_15">Content Creation & Management </h3>
                    <!-- <p>Her extensive perceived may any sincerity extremity.</p>  -->
                </div>
            </div>
            
            
            <!-- <div class="teammates row bottom_90 top_45">
                <div class="col-md-4 team">
                    <img src="img/team-1.jpg" alt="">
                    <span class="name">Nicky Byers</span>
                </div>
                <div class="col-md-4 team">
                    <img src="img/team-2.jpg" alt="">
                    <span class="name">Arthur J. Dawson</span>
                </div>
                <div class="col-md-4 team">
                    <img src="img/team-3.jpg" alt="">
                    <span class="name">Rosa Dole</span>
                </div>
            </div> -->
            
            
        </div>
        
        
        
        <!-- testimonials -->
        <!-- <div class="col-lg-4 offset-lg-4 text-center">
            <div class="owl-carousel owl-theme testimonials" data-items-desktop="1" data-items-desktop-small="1" data-items-tablet="1" data-items-tablet-small="1">
                <div class="item">
                   <p>"The very best. I just can't get enough of dark me. I want to get a T-Shirt with dark me on it so I can show it off to everyone. It's the perfect solution for our business."</p>
                    <span>Evonne L.</span>
                </div>
                <div class="item">
                   <p>"Very easy to use. Very easy to use. Not able to tell you how happy I am with tavonline."</p>
                    <span>- Vittoria B.</span>
                </div>
                <div class="item">
                   <p>"After using tavonline my business skyrocketed! This is simply unbelievable! We're loving it."</p>
                    <span>Ahmed T.</span>
                </div>
            </div>
        </div> -->
        
        <!-- Social Links -->
        <!-- <div class="col-lg-4 offset-lg-4 top_90 bottom_60">
            <ul class="list-style row text-center">
                <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><a href="#">TWITTER<span>amokachidan</span></a></li>
                <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><a href="#">INSTAGRAM<span>daniel.85</span></a></li>
                <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><a href="#">DRIBBBLE<span>daniel.85</span></a></li>
            </ul>
        </div> -->
    </div>
    
</div>
    
</div><!-- wrapper end -->


{% endblock content %}

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>


<title>{% block title %} {% endblock title %} - Script Desk </title>
<meta charset="UTF-8">
<meta name="description" content="Script Desk">
<meta name="keywords" content="script desk, olabanji albert, olushola albert, technology, technology in nigeria, nigeria ">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- CSS
================================================== -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/reset.css' %}"/>
<link rel="stylesheet" href="{% static 'css/style.css' %}"/>

<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
    
<!-- Font icons -->
<link rel="stylesheet" href="{% static 'icon-fonts/fontawesome-5.0.6/css/fontawesome-all.min.css' %}"/>

<!-- Google Fonts
================================================== -->
<link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700" rel="stylesheet">
</head>

<body>
    
<!-- Preloader -->
<div class="preloader">
    <div class="outer">
        <div class="inner">
            <div class="percentage"></div>                          
        </div>
    </div>
</div>
<!--/Preloader -->  
    

<!-- HEADER
==================================================-->
<header>
	<div class="logo float-left">
		<img src="{% static 'img/script_desk_one.svg' %}" height="38px" width="auto" alt="">
	</div> 
	<div class="nav-icon float-right">
		<span></span>
		<span></span>
		<span></span>
	</div>
</header>
 
<!-- Full Menu -->
<div class="full-menu">
	<div class="fullmenu-content">
		<ul class="page-menu">
			<li><a class="active" href="/">Home</a></li>
			<li><a href="{% url 'home:who-we-are' %}">Who We Are </a></li>
			<li><a href="{% url 'home:start-a-project' %}">Start A Project </a></li>
			
			<li class="social">
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-dribbble"></i></a>
                <a href="#"><i class="fab fa-telegram-plane"></i></a>
			</li>
		</ul>
	</div>
	<a href="#0" class="modal-close"></a>
</div>
<div class="cd-transition-layer visible opening"> 
	<div class="bg-layer"></div>
</div><!-- Ink Transition -->

<div class="wrapper">
    {% block content %}


    {% endblock content %}
<footer>
    <div class="container padding_90">
        <div class="row">
            <div class="col-lg-9 col-md-9">
                <div class="social">
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                
                </div><br>
                <p>No 6, Lara Ademola Street, Lekki, Lagos State</p><br>
                <p>+234 704 241 1717, +234 813 749 8991</p>
                <p>info@scriptdeskng.com</p>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="uptotop">up to top</div>
            </div>
        </div>
    </div>
</footer>
    
</div>



<!-- Javascripts -->
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/packery-mode.pkgd.min.js' %}"></script>  
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>      
<script src="{% static 'js/particles.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/modernizr.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

home/templates/home/blogs.html
<!DOCTYPE html>
<html lang="en">
<head>

<!-- Basic Page Needs
================================================== -->
<title>Amokachi Portfolio Template</title>
<meta charset="UTF-8">
<meta name="description" content="Amokachi Portfolio Template">
<meta name="keywords" content="personal, portfolio">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- CSS
================================================== -->
<link rel="stylesheet" href="css/bootstrap.min.css"/>    
<link rel="stylesheet" href="css/owl.carousel.min.css">
<link rel="stylesheet" href="css/owl.theme.default.min.css">
<link rel="stylesheet" href="css/reset.css"/>
<link rel="stylesheet" href="css/style.css"/>

<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Fonts
================================================== -->
<link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700" rel="stylesheet">

<!-- Icon Fonts
================================================== -->
<link rel="stylesheet" href="icon-fonts/etlinefont/style.css"/>
    
<!-- Font icons -->
<link rel="stylesheet" href="icon-fonts/fontawesome-5.0.6/css/fontawesome-all.min.css"/>

</head>

<body>
    
    
<!-- Preloader -->
<div class="preloader">
    <div class="outer">
        <div class="inner">
            <div class="percentage"></div>                          
        </div>
    </div>
</div>
<!--/Preloader -->  
    
<!-- HEADER
================================================== -->
<header>
	<div class="logo float-left">
		<img src="img/logo.png" alt="">
	</div> 
	<div class="nav-icon float-right">
		<span></span>
		<span></span>
		<span></span>
	</div>
</header>

<!-- Full Menu -->
<div class="full-menu">
	<div class="fullmenu-content">
		<ul class="page-menu">
            <li><a href="index.html">Home</a></li>
            <li><a href="about.html">About </a></li>
            <li><a class="active" href="blogs.html">Blog Posts</a></li>
            <li><a href="contact.html">Contact</a></li>
			<li><a href="https://themeforest.net/item/amokachi-creative-portfolio-html-template/22605799">Buy Now</a></li>
			<li class="social">
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-dribbble"></i></a>
                <a href="#"><i class="fab fa-telegram-plane"></i></a>
			</li>
		</ul>
	</div>
	<a href="#0" class="modal-close"></a>
</div>
<div class="cd-transition-layer visible opening"> 
	<div class="bg-layer"></div>
</div><!-- Ink Transition -->

<div class="wrapper">

<!-- PAGE CONTENT
================================================== -->
<div class="container">
    <div class="page-content about-page">
        <div class="page-title top_90 bottom_60">
            <h1 class="title">Blog Posts</h1>
            <div class="zigzag">
                <svg viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns="http://www.w3.org/2000/svg">
                 <path d="M1.357,12.26 10.807,2.81 20.328,12.332
                    29.781,2.879 39.223,12.321 48.754,2.79  58.286,12.321"/>
                </svg>
            </div>
        </div>
    </div>
    <!-- blog posts -->
    <div class="col-lg-8 offset-lg-2">
        <!-- a post -->
        <div class="blog-post bottom_120">
            <a class="blog-link" href="single_blog.html">
                <figure class="bottom_60">
                    <img src="img/blog-2.jpg" alt="">
                </figure>
            </a>
            <div class="col-lg-10 offset-lg-1 content-outter">
                <div class="blog-categories bottom_15">
                    <a href="#">photography</a>
                    <a href="#">aeneral</a>
                </div>
                <a class="blog-link" href="single_blog.html"><h2 class="blog-title bottom_15">Vaccines Against H.I.V., Malaria and Tuberculosis Unlikely, Study Says</h2>
                    <p class="blog-text">In varius varius justo, eget ultrices mauris rhoncus non. Morbi tristique, mauris eu imperdiet bibendum, velit diam iaculis velit, in ornare massa enim at lorem. Etiam risus diam, porttitor vitae ultrices quis, dapibus id dolor. Morbi venenatis lacinia rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non enim ut enim fringilla adipiscing id ...</p>
                    <span class="blog-info top_15">George Michael, March 2, 2018</span>
                </a>
            </div>
        </div>
        <!-- a post -->
        <div class="blog-post bottom_120">
            <a class="blog-link" href="single_blog.html">
                <figure class="bottom_60">
                    <img src="img/blog-1.jpg" alt="">
                </figure>
            </a>
            <div class="col-lg-10 offset-lg-1 content-outter">
                <div class="blog-categories bottom_15">
                    <a href="#">photography</a>
                    <a href="#">aeneral</a>
                </div>
                <a class="blog-link" href="single_blog.html"><h2 class="blog-title bottom_15">Vaccines Against H.I.V., Malaria and Tuberculosis Unlikely, Study Says</h2>
                    <p class="blog-text">In varius varius justo, eget ultrices mauris rhoncus non. Morbi tristique, mauris eu imperdiet bibendum, velit diam iaculis velit, in ornare massa enim at lorem. Etiam risus diam, porttitor vitae ultrices quis, dapibus id dolor. Morbi venenatis lacinia rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non enim ut enim fringilla adipiscing id ...</p>
                    <span class="blog-info top_15">George Michael, March 2, 2018</span>
                </a>
            </div>
        </div>
        <!-- a post -->
        <div class="blog-post bottom_120">
            <a class="blog-link" href="single_blog.html">
                <figure class="bottom_60">
                    <img src="img/blog-3.jpg" alt="">
                </figure>
            </a>
            <div class="col-lg-10 offset-lg-1 content-outter">
                <div class="blog-categories bottom_15">
                    <a href="#">photography</a>
                    <a href="#">aeneral</a>
                </div>
                <a class="blog-link" href="single_blog.html"><h2 class="blog-title bottom_15">Vaccines Against H.I.V., Malaria and Tuberculosis Unlikely, Study Says</h2>
                    <p class="blog-text">In varius varius justo, eget ultrices mauris rhoncus non. Morbi tristique, mauris eu imperdiet bibendum, velit diam iaculis velit, in ornare massa enim at lorem. Etiam risus diam, porttitor vitae ultrices quis, dapibus id dolor. Morbi venenatis lacinia rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non enim ut enim fringilla adipiscing id ...</p>
                    <span class="blog-info top_15">George Michael, March 2, 2018</span>
                </a>
            </div>
        </div>
    </div>
    
</div>
    
</div>

<!-- FOOTER
================================================== -->
<footer>
	<div class="container padding_90">
		<div class="row">
			<div class="col-lg-9">
				<div class="social">
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-dribbble"></i></a>
                    <a href="#"><i class="fab fa-telegram-plane"></i></a>
				</div><br>
				<p>1444 S. Alameda Street Los Angeles, California 90021</p><br>
				<p>0216 514 25 25</p>
				<p>contact@darkme.com</p>
			</div>
			<div class="col-lg-3">
				<div class="uptotop">up to top</div>
			</div>
		</div>
	</div>
</footer>

<!-- Javascripts -->
<script src="js/jquery-2.1.4.min.js"></script>
<script src="js/isotope.pkgd.min.js"></script>
<script src="js/packery-mode.pkgd.min.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/modernizr.js"></script>   
<script src="js/main.js"></script>


</body>
</html>

home/templates/home/contact.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %} Start A Project  {% endblock title %}

{% block content %}

<div class="container">
    <div class="page-content about-page">
        <div class="page-title top_90">
            <h1 class="title">Start A Project </h1>
            <div class="zigzag">
                <svg viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns="http://www.w3.org/2000/svg">
                 <path d="M1.357,12.26 10.807,2.81 20.328,12.332
                    29.781,2.879 39.223,12.321 48.754,2.79  58.286,12.321"/>
                </svg>
            </div>
        </div>
    </div>
    <!-- Contact -->
    <div class="col-lg-6 offset-lg-3">
        <!-- Send a message -->
        <div class="form top_60 bottom_120 text-center">
            <h2 class="form-title bottom_60">Send a Message</h2>
            <form class="contact-form top_30" method="POST">
                {% csrf_token %}
                <div class="row">
                    <!--Name-->
                    <div class="col-md-6">
                        
                        {{form.name}}
                    </div>
                    <!--Email-->
                    <div class="col-md-6">
                      
                        {{form.email}}
                    </div>
                    <div class="col-md-12">
                        <!--Message-->
                        {{form.msg}}
                        
                        <button id="con_submit" class="form-btn" type="submit">SUBMIT</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <!-- Social Links -->
    <div class="col-lg-6 offset-lg-3 top_90 bottom_60">
        <ul class="list-style row text-center">
            <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><a href="#">EMAIL<span>info@scriptdeskng.com</span></a></li>
            <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><a href="#">ADDRESS<span>No 6, Lara Ademola Street, Lekki, Lagos State</span></a></li>
            <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><a href="#">PHONE<span><p>+234 704 241 1717, +234 813 749 8991</p></span></a></li>
        </ul>
    </div>
    
</div>
    
</div>
{% endblock content %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %} Homepage {% endblock title %}

{% block content %}
<section class="main">
	<div class="main-content">
        <!-- <span class="hello">Hello World!</span> -->
		<h1 class="main-title">Helping your business grow with our extensive experience in web and digital marketing, content management and programming, platform development and management</h1>
		<div class="social">
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
      
		</div>
	</div>
	<a class="down-arrow">
		<div class="down-inner">
			<img src="{% static 'img/icons/down-arrow.svg' %}" alt="">
			<div class="line"></div>
		</div>
	</a>

    <div id="particles-js"></div>
</section>

<!-- PORTFOLIO CONTENT 
================================================== -->
<section class="content bottom_90">
    <div class="container">
        
        <div class="vf">
            <div class="zigzag">
                <svg viewBox="0 0 69.172 14.975" width="37" height="28" y="0px" x="0px" xmlns="http://www.w3.org/2000/svg">
                 <path d="M1.357,12.26 10.807,2.81 20.328,12.332
                    29.781,2.879 39.223,12.321 48.754,2.79  58.286,12.321"/>
                </svg>
            </div>
            <p>View Filter</p>
        </div>
        
        <div class="portfolio_filter">
            <ul>
                <li><a class="select-cat" data-filter="*" href="#">All Works</a></li>
                <li><a data-filter=".web-design" href="#">Web Design</a></li>
                <li><a data-filter=".branding" href="#">Branding</a></li>
                <li><a data-filter=".photography" href="#">Photography</a></li>
            </ul>   
        </div>
            
        <div class="isotope_items row">
            <!-- Item -->
            <a href="#" class="single_item web-design col-md-6">
                <figure>
                <img src="{% static 'img/portfolio/01.jpg' %}" alt="">
                     <figcaption>
                                <ul>
                                    <!-- <li> <span>web dign</span> </li> -->
                                    <li><h3 class="title">Web & Digital Marketing</h3></li>
                                </ul>
                    </figcaption>
                </figure>
            </a>
            <!-- Item -->
            <a href="#" class="single_item photography col-md-6">
                <figure>
                <img src="{% static 'img/portfolio/02.jpg' %}" alt="">
                     <figcaption>
                                <ul>
                                    <!-- <li> <span>photography</span> </li> -->
                                    <li><h3 class="title">Content Managent & Marketing</h3></li>
                                </ul>
                    </figcaption>
                </figure>
            </a>
            <!-- Item -->
            <!-- <a href="#" class="single_item web-design col-md-3">
                <figure>
                <img src="{% static 'img/portfolio/04.jpg' %}" alt="">
                     <figcaption>
                                <ul>
                                 
                                    <li><h3 class="title">Branding</h3></li>
                                </ul>
                    </figcaption>
                </figure>
            </a> -->
            <!-- Item -->
            <!-- <a href="#" class="single_item branding col-md-3">
                <figure>
                <img src="{% static 'img/portfolio/05.jpg' %}" alt="">
                     <figcaption>
                                <ul>
                                  
                                    <li><h3 class="title">Branding</h3></li>
                                </ul>
                    </figcaption>
                </figure>
            </a> -->
            <!-- Item -->
            <a href="#" class="single_item branding col-md-6">
                <figure>
                <img src="{% static 'img/portfolio/03.jpg' %}" alt="">
                     <figcaption>
                                <ul>
                          
                                    <li><h3 class="title">Platform Development & Management</h3></li>
                                </ul>
                    </figcaption>
                </figure>
            </a>
            <!-- Item -->
            <a href="#" class="single_item photography col-md-6">
                <figure>
                <img src="{% static 'img/portfolio/06.jpg' %}" alt="">
                     <figcaption>
                                <ul>
                        
                                    <li><h3 class="title">Branding</h3></li>
                                </ul>
                    </figcaption>
                </figure>
            </a>
        </div>
    </div>
</section>

{% endblock content %}